"""initial schema: indexing_jobs, chunks, outbox_events

Revision ID: 436a67939427
Revises:
Create Date: 2026-08-17 19:31:03.197454

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "436a67939427"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("start_token", sa.Integer(), nullable=False),
        sa.Column("end_token", sa.Integer(), nullable=False),
        sa.Column("has_overlap", sa.Boolean(), nullable=False),
        sa.Column("forced_split", sa.Boolean(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("point_id", sa.String(length=36), nullable=False),
        sa.Column("source_content_type", sa.String(length=100), nullable=False),
        sa.Column("source_content_hash", sa.String(length=64), nullable=False),
        sa.Column("extractor_type", sa.String(length=50), nullable=False),
        sa.Column("extractor_version", sa.String(length=20), nullable=False),
        sa.Column("embedding_model", sa.String(length=100), nullable=False),
        sa.Column("chunking_version", sa.String(length=50), nullable=False),
        sa.Column("section_type", sa.String(length=50), nullable=True),
        sa.Column("section_title", sa.String(length=500), nullable=True),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.Column("hierarchy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_chunks_point_id", "chunks", ["point_id"], unique=True)
    op.create_index("ix_chunks_section_type", "chunks", ["tenant_id", "section_type"], unique=False)
    op.create_index(
        "ix_chunks_tenant_document",
        "chunks",
        ["tenant_id", "document_id", "version_id"],
        unique=False,
    )
    op.create_table(
        "indexing_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_chunks", sa.Integer(), nullable=True),
        sa.Column("processed_chunks", sa.Integer(), nullable=False),
        sa.Column("embedding_model", sa.String(length=100), nullable=False),
        sa.Column("chunking_version", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_indexing_jobs_document_lookup",
        "indexing_jobs",
        ["tenant_id", "document_id", "version_id"],
        unique=True,
    )
    op.create_index("ix_indexing_jobs_tenant_id", "indexing_jobs", ["tenant_id"], unique=False)
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=200), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_outbox_events_pending",
        "outbox_events",
        ["status", "created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_outbox_events_pending",
        table_name="outbox_events",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("outbox_events")
    op.drop_index("ix_indexing_jobs_tenant_id", table_name="indexing_jobs")
    op.drop_index("ix_indexing_jobs_document_lookup", table_name="indexing_jobs")
    op.drop_table("indexing_jobs")
    op.drop_index("ix_chunks_tenant_document", table_name="chunks")
    op.drop_index("ix_chunks_section_type", table_name="chunks")
    op.drop_index("ix_chunks_point_id", table_name="chunks")
    op.drop_table("chunks")
    # ### end Alembic commands ###
